[project]
name = "modulo-users"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Theo Sementa", email = "theosementa@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.20.0",
    "grpcio>=1.84.0",
    "modulo-common",
    "psycopg>=3.3.6",
    "pydantic-settings>=2.15.0",
    "sqlalchemy>=2.1.1",
]

[project.scripts]
modulo-users = "modulo_users.server:serve"

[build-system]
requires = ["uv_build>=0.11.21,<0.12.0"]
build-backend = "uv_build"

[tool.uv.sources]
modulo-common = { git = "https://github.com/modulo-app/Modulo-Common", tag = "v0.3.1" }

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
